module.exports = {
	'apple':               'Apple',
	'TCL':                 'Alcatel',
	'BullittGroupLimited': 'Bullit Group',
	'CROSSCALL':           'Crosscall',
	'KYOCERA':             'Kyocera',
	'LENOVO':              'Lenovo',
	'LGE':                 'LG Electronics',
	'M3Mobile':            'M3 Mobile',
	'HMD Global':          'Nokia (owned by HMD Global)',
	'PANASONIC':           'Panasonic',
	'POINTMOBILE':         'PointMobile',
	'SHARP':               'Sharp',
	'Sonimtech':           'Sonim Technologies',
	'Unitech_Electronics': 'Unitech',
	'Urovo':               'Urovo Technology',
	'WIKO':                'Wiko',
	'Zebra Technologies':  'Zebra',
};
